### ISSUE TITLE
Color Guess Exit

### ISSUE THREAD

**Issue by RogueMaster** [leedave/Leeds-Flipper-Zero-Applications#10]
Latest color guess changes seem to leave it in a state that it just exits...

**Comment by leedave** [comment]
Strange
Comparing all files from my git with my fap testing env. I found one difference, an old version of digits.h (new file is moved to /helpers folder), tested it on OFW with that file in it and still worked. Removed the duplicate file for now.

**Comment by leedave** [comment]
I see minimal differences in some of your header files, but to me it just looks like formatting diffs. Tried copying the version from your Git to my setup and it also ran well. 

The only other thing I can imagine is that some function has a naming conflict with something new in your FW that is not in OFW. Not sure how I can help.

**Comment by RogueMaster** [comment]
Will look into further, it seems like the prior version was also exiting...

**Comment by leedave** [comment]
Exiting or crashing flipper? Still haven‘t managed to reproduce.

**Comment by RogueMaster** [comment]
It exits on open. I tried older RM versions and older color guess versions. All don't open and just exit once trying to open. I have commented the app on RM for now till you/we can figure it out 😄

**Comment by leedave** [comment]
Ok, managed to reproduce. Needed a full install of RM for this to happen. Trying to narrow down what is causing it, as it want it to run on all FW types, not only OFW.

**Comment by leedave** [comment]
Found it!

in the main app() function this code doesn't affect anything in OFW, but executes (and exits) in RM

`
if(!furi_hal_region_is_provisioned()) {
        boilerplate_app_free(app);
        return 1;
    }
`

Solved by commenting it out as it serves no real purpose. 

btw. found the same problem in the **Boilerplate**. 

Fixed both in your latest release and sent a pull-request to **flipperzero-firmware-wPlugins**.
