### ISSUE TITLE
xRemote Build Errors

### ISSUE THREAD

**Issue by RogueMaster** [leedave/Leeds-Flipper-Zero-Applications#11]
Your xremote seems to have a build error...

applications/plugins/xremote/scenes/xremote_scene_scene_1.c: In function 'xremote_scene_scene_1_on_event':
applications/plugins/xremote/scenes/xremote_scene_scene_1.c:55:14: error: 'XRemoteCustomEventScene1Left' undeclared (first use in this function); did you mean 'XRemoteCustomEventScene2Left'?
   55 |         case XRemoteCustomEventScene1Left:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XRemoteCustomEventScene2Left
applications/plugins/xremote/scenes/xremote_scene_scene_1.c:56:14: error: 'XRemoteCustomEventScene1Right' undeclared (first use in this function); did you mean 'XRemoteCustomEventScene2Right'?
   56 |         case XRemoteCustomEventScene1Right:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XRemoteCustomEventScene2Right
applications/plugins/xremote/scenes/xremote_scene_scene_1.c:58:14: error: 'XRemoteCustomEventScene1Up' undeclared (first use in this function); did you mean 'XRemoteCustomEventScene2Up'?
   58 |         case XRemoteCustomEventScene1Up:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XRemoteCustomEventScene2Up
applications/plugins/xremote/scenes/xremote_scene_scene_1.c:59:14: error: 'XRemoteCustomEventScene1Down' undeclared (first use in this function); did you mean 'XRemoteCustomEventScene2Down'?
   59 |         case XRemoteCustomEventScene1Down:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XRemoteCustomEventScene2Down
applications/plugins/xremote/scenes/xremote_scene_scene_1.c:61:14: error: 'XRemoteCustomEventScene1Back' undeclared (first use in this function); did you mean 'XRemoteCustomEventScene2Back'?
   61 |         case XRemoteCustomEventScene1Back:
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              XRemoteCustomEventScene2Back

**Comment by leedave** [comment]
Thanks for the note. 

The file xremote_scene_scene_1.c was removed a while ago (started with boilerplate, replacing parts not needed). Probably still in your copy of the code. 

You can use this as educational example, but I wouldn't recommend it implementing it until I merge stuff to the **main** branch. Everything in **feature/branches** is in development. Once in **main** you can consider it a version ready for use.

Current situation in feature/xremote
- It doesn't not do anything yet, I'm currently just working on the UI
- More files will be replaced (exampe *_scene_2.*)
