### ISSUE TITLE
Apps not building on toolchain 46.0 f7

### ISSUE THREAD

**Issue by doomwastaken** [leedave/Leeds-Flipper-Zero-Applications#35]
Greetings! I am from Flipper Devices team and would like to say thank you for submitting your apps to the catalog. We are finalizing API prior to 1.0 release and currently your application cannot be built for latest toolchain. Currently we are testing 0.95.0-rc and app is not being built for that version. 

We are currently working on automating the messages from our build server, so this one is manual :)

If you have any questions, just tag me

**Comment by leedave** [comment]
Thank you for your support. The Update was submitted to the catalog and approved by you.
